# Generated by Django 3.2 on 2021-04-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu_type', models.CharField(max_length=50)),
                ('usb_address', models.CharField(max_length=200)),
                ('net_address', models.CharField(max_length=200)),
                ('wifi_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('voltage', models.IntegerField(default=12)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralina.board')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('voltage', models.IntegerField(default=220)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralina.board')),
            ],
        ),
    ]
