# Generated by Django 3.2 on 2021-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pump',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
