# Generated by Django 3.2.1 on 2021-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchtype',
            name='mode',
            field=models.CharField(choices=[('I', 'Input'), ('O', 'Output')], default='I', max_length=1),
        ),
    ]
