# Generated by Django 3.2 on 2021-04-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0002_auto_20210421_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='switch',
            name='on_hi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='pin',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Pump',
        ),
        migrations.AddField(
            model_name='switch',
            name='switchType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='centralina.switchtype'),
            preserve_default=False,
        ),
    ]
