# Generated by Django 3.2.1 on 2021-05-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0002_switchtype_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='state',
        ),
    ]
