# Generated by Django 3.2 on 2021-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0003_auto_20210421_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='voltage',
        ),
        migrations.AddField(
            model_name='switchtype',
            name='voltage',
            field=models.IntegerField(default=12),
        ),
    ]
