# Generated by Django 3.2.1 on 2021-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0003_remove_switch_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='pin_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='state',
            field=models.CharField(choices=[('', 'Unknow'), ('open', 'Open'), ('close', 'Close')], default='', max_length=5),
        ),
    ]
