# Generated by Django 3.2.1 on 2021-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0004_auto_20210505_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='on_hi',
        ),
        migrations.AddField(
            model_name='switchtype',
            name='open_value',
            field=models.BooleanField(default=True),
        ),
    ]
