# Generated by Django 3.2 on 2021-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0004_auto_20210421_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cpu_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='net_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='usb_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='wifi_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
