# Generated by Django 3.2.1 on 2021-05-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0005_auto_20210505_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('pin', models.IntegerField(default=1)),
                ('updated', models.DateTimeField()),
                ('varType', models.CharField(choices=[('', 'Unknow'), ('int', 'Int'), ('real', 'Real'), ('string', 'String')], default='string', max_length=6)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralina.board')),
            ],
        ),
    ]
