# Generated by Django 3.2 on 2021-04-22 12:57

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0005_auto_20210422_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='state',
            field=models.CharField(default=io.open, max_length=10),
            preserve_default=False,
        ),
    ]
