# Generated by Django 3.2.1 on 2021-05-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0006_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='varType',
            field=models.CharField(choices=[('', 'Unknow'), ('text_bool', 'Text Bool'), ('text_int', 'Text Int'), ('text_real', 'Text Real'), ('text_string', 'Text String')], default='text_string', max_length=12),
        ),
    ]
