# Generated by Django 3.2.1 on 2021-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0007_alter_variable_vartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='varType',
            field=models.CharField(choices=[('', 'Unknow'), ('text_bool', 'Text Bool'), ('text_int', 'Text Int'), ('text_real', 'Text Real'), ('text_string', 'Text String'), ('btn_toggle', 'Btn Toggle')], default='text_string', max_length=12),
        ),
    ]
