# Generated by Django 3.2.1 on 2021-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0008_alter_variable_vartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enable_cpu',
            field=models.BooleanField(default=True),
        ),
    ]
