# Generated by Django 3.2.1 on 2021-05-12 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0009_board_enable_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='VariableHistory',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralina.variable')),
            ],
        ),
    ]
