# Generated by Django 3.2.1 on 2021-05-12 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0010_auto_20210512_2300 copy'),
    ]

    operations = [
        #migrations.RunSQL("SELECT create_hypertable('centralina_variablehistory', 'time');"),
        #migrations.RunSQL(
        #    "ALTER TABLE centralina_variablehistory SET (timescaledb.compress, timescaledb.compress_segmentby = 'variable_id');"
        #),
        #migrations.RunSQL(
        #    "SELECT add_compress_chunks_policy('centralina_variablehistory', INTERVAL '7 days');"
        #),
    ]
