# Generated by Django 3.2.1 on 2021-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0011_time_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='saveMode',
            field=models.CharField(choices=[('', 'None'), ('0', 'Always'), ('10', '10 secs'), ('30', '30 secs'), ('60', '1 min'), ('600', '10 min'), ('3600', '1 hour')], default='', max_length=5),
        ),
    ]
