# Generated by Django 3.2.1 on 2021-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0013_alter_variable_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='varType',
            field=models.CharField(choices=[('', 'Unknow'), ('text_bool', 'Text Bool'), ('text_int', 'Text Int'), ('text_real', 'Text Real'), ('text_string', 'Text String'), ('btn_toggle', 'Btn Toggle'), ('json', 'Json')], default='text_string', max_length=12),
        ),
    ]
