# Generated by Django 3.2.1 on 2021-05-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0014_alter_variable_vartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='startupMode',
            field=models.CharField(choices=[('', 'None'), ('db', 'Db'), ('hd', 'Hardware')], default='', max_length=2),
        ),
    ]
