# Generated by Django 3.2.1 on 2021-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0015_variable_startupmode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='usb_address',
            new_name='usb_address_lx',
        ),
        migrations.AddField(
            model_name='board',
            name='usb_address_win',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='startupMode',
            field=models.CharField(choices=[('', 'None'), ('db', 'Db'), ('hw', 'Hardware')], default='', max_length=2),
        ),
    ]
