# Generated by Django 3.2.1 on 2021-06-02 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0016_auto_20210601_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAnalysis',
            fields=[
                ('tank', models.CharField(max_length=20)),
                ('ph', models.FloatField(default=0)),
                ('ec', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
            ],
        ),
    ]
