# Generated by Django 3.2.1 on 2021-06-03 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0017_wateranalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabLog',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
