# Generated by Django 3.2.1 on 2021-06-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0018_lablog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAI',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=20)),
                ('operationType', models.CharField(choices=[('ec_add', 'Ec Add'), ('ph_add', 'Ph Add'), ('water_add', 'Water Add')], default='ec_add', max_length=10)),
                ('lab_liters', models.FloatField(default=0)),
                ('estimate_tank_liters', models.FloatField(default=0)),
                ('start_value', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('final_value', models.FloatField(default=0)),
                ('value_to_ml_factor', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabPumpCalibrate',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('id', models.IntegerField(default=0)),
                ('time_secs', models.IntegerField(default=0)),
                ('filled_ml', models.IntegerField(default=0)),
                ('ml_at_seconds', models.FloatField(default=0)),
            ],
        ),
    ]
