# Generated by Django 3.2.1 on 2021-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0019_labai_labpumpcalibrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('additiveType', models.CharField(choices=[('PH_DOWN', 'Ph Down'), ('PH_UP', 'Ph Up'), ('FERTILIZER', 'Fertilizer'), ('WATER_WELL', 'Water Well'), ('WATER_OSMOTIC', 'Water Osmotic')], default='PH_DOWN', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='switch',
            name='startupMode',
            field=models.CharField(choices=[('db', 'Db'), ('hw', 'Hardware')], default='hw', max_length=2),
        ),
    ]
