# Generated by Django 3.2.1 on 2021-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0020_auto_20210607_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpumpcalibrate',
            name='calibrateType',
            field=models.CharField(choices=[('TIME', 'Time'), ('WEIGHT', 'Weight')], default='TIME', max_length=10),
        ),
        migrations.AddField(
            model_name='labpumpcalibrate',
            name='filled_gr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labpumpcalibrate',
            name='gr_at_seconds',
            field=models.FloatField(default=0),
        ),
    ]
