# Generated by Django 3.2.1 on 2021-06-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralina', '0021_auto_20210609_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labpumpcalibrate',
            old_name='filled_gr',
            new_name='filled_gr_end',
        ),
        migrations.AddField(
            model_name='labpumpcalibrate',
            name='filled_gr_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labpumpcalibrate',
            name='gr_lost',
            field=models.IntegerField(default=0),
        ),
    ]
